### GET request to example server
GET localhost:8080/chat
### GET request to example server
GET localhost:8080/stream
###
GET localhost:8080/joke
###
GET localhost:8080/acme/chat?message=What are te top 5 NBA teams?
###
GET localhost:8080/acme/chat?message=How to transfer to external account?
###
GET localhost:8080/posts/new?topic=dogs
###
GET localhost:8080/posts/new
###
GET localhost:8080/vacation/unstructured
###
GET localhost:8080/vacation/structured
###
GET localhost:8080/image-to-text
###
GET localhost:8080/generate-image
###
GET localhost:8080/generate-image?prompt=View of Paris
###
GET localhost:8080/speak
###
GET localhost:8080/speak?prompt=This is a test generating speech from a text prompt.
###
GET localhost:8080/memory?message=What's my name?
###
GET localhost:8080/models
###
GET localhost:8080/models/stuff-the-prompt
###